# Generated by Django 3.2.4 on 2021-07-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='name',
        ),
    ]
