# Generated by Django 3.2.4 on 2021-07-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_remove_promo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
